let CmsContext = {
        language: '',
        result: {
            "sidebarContent": "Content goes here",
            "dataFiles": "Data Files",
            "dataMappingSubTitle": "Manage your mapping of your data files.",
            "dataMappingTitle": "Data Mapping",
            "pageTitle": "Character replacement",
            "option4": "Space",
            "option1": "Remove fragments from file",
            "pageSubTitle": "Configure what characters and string values you would like replaced.",
            "datareview": "Data Preview",
            "detectDataLabel": "When duplicate data is detected:",
            "option2": "Stop processing files and alert me",
            "showRowsPrev": "show previous 10 rows",
            "title": "When unexpected line breaks are detected:",
            "option3": "Attempt to join",
            "stopProcessing": "Stop processing files and alert me",
            "subOption2": "Stop processing file and alert me",
            "option5": "Other",
            "showRowsNxt": "show next 10 rows",
            "withThis": "With this",
            "titleHeader": "Header and footer",
            "backToBoard": "Back to Dashboard",
            "titleBreakLine": "Unexpected line breaks",
            "titleFieldConfig": "Field alias and configuration",
            "removeDuplicateRow": "Remove duplicate rows",
            "removeChar": "Character Removal",
            "description": "Configure what you would like to happen when unexpected line breaks are detected.",
            "subOption1": "Remove fragments from file",
            "replace": "Replace this",
            "removData": "Enter characters to be removed from the data",
            "inputPlaceholder": "Input text",
            "addButton": "Add",
            "viewHeader": "View/edit file header and footer",
            "titleDelimiter": "Delimiter",
            "viewDelimiter": "View/edit file delimiter",
            "titleReplaceChar": "Character Replacement",
            "viewFieldConfig": "View/edit field alias and configuration",
            "titleDuplicateData": "Duplicate Data",
            "drawerTitle": "Drawer title",
            "popOverContent": "Manage validation rules",
            "dataMappingColumn2": "Data Provider",
            "validationRulePageTitle": "Validation Rules",
            "backToDashboard": "Back to Dashboard",
            "dataMappingColumn1": "Connection Name",
            "file": "File",
            "SubTitle": "Configure what characters and string values you would like replaced.",
            "dialogTitle": "Alert",
            "connection": "Connection",
            "dialogHeading": "Are you sure! Your data will be lost, please save the data first",
            "delimiterSubTitle": "Specify the file delimiter if the data below is not displayed correctly.",
            "delimiterOption1": "Tab",
            "delimiterOption5": "Other",
            "delimiterDatareview": "Data Preview",
            "manageRecordsShowRowsNxt": "show next 10 rows",
            "manageRecordsShowRowsPrev": "show previous 10 rows",
            "delimiterTitle": "Confirm file delimiter",
            "duplicateDataOption1": "Remove duplicate rows",
            "delimiterOption4": "Space",
            "unexpectedLineBreakOption1": "Remove fragments from file",
            "duplicateDataOption2": "Stop processing files and alert me",
            "manageRecordsSubTitle": "All rows above the file header will be ignored. The footer row and any rows below will also be ignored.",
            "unexpectedLineBreakSubOption2": "Stop processing file and alert me",
            "dialogButtonText": "Go Back Anyway",
            "duplicateDataDetected": "When duplicate data is detected:",
            "ruleSubHeading": "You do not have any rules configured.",
            "replaceCharacterInputPlaceholder": "Input text",
            "unexpectedLineBreakDetected": "When unexpected line breaks are detected:",
            "delimiterOption2": "Semicolon",
            "unexpectedLineBreakSubOption1": "Remove fragments from file",
            "removeCharacterInputPlaceholder": "Enter Characters",
            "delimiterShowRowsNxt": "show next 10 rows",
            "unexpectedLineBreakOption2": "Stop processing files and alert me",
            "replaceCharacterWithThis": "With this",
            "delimiterOption3": "Comma",
            "duplicateDataTitle": "Duplicate data",
            "removeCharacterData": "Enter characters to be removed from the data",
            "unexpectedLineBreakTitle": "Unexpected line breaks",
            "manageRecordsTitle": "Confirm file header and footer",
            "configureFieldsAlert": "Please confirm file header to proceed",
            "unexpectedLineBreakOption3": "Attempt to join",
            "noEndDate": "No end date - apply rule perpetually",
            "replaceCharacterTitle": "Character replacement",
            "replaceCharacterSubTitle": "Configure what characters and string values you would like replaced.",
            "duplicateDataSubTitle": "Configure what you would like to happen when duplicate data is detected.",
            "removeCharacterTitle": "Character removal",
            "replaceCharacterAddButton": "Add",
            "configureFieldsDisplaydata": "Sample data Test",
            "applyDate": "Apply rule to data dated from:",
            "unexpectedLineBreakSubTitle": "Configure what you would like to happen when unexpected line breaks are detected.",
            "earlyDate": "Earliest dated data - apply to all historical data",
            "addButtonText": "Add",
            "configureFieldsTitle": "Field alias and configuration",
            "cancel": "Cancel",
            "unexpectedLineBreakSubHeading": "If join fails:",
            "stopDate": "Stop applying rule to data dated from: ",
            "replaceCharacterText": "Replace this",
            "rulesHeader": "Validation Rules",
            "removeCharacterSubTitle": "Configure what characters/strings you want removed from your data.",
            "configureFieldsDisplayonly": "Display only unmapped columns",
            "today": "Today",
            "saveExit": "Save and exit"
        },
        "__typename": "strapiOutput"
    }
;

module.exports = CmsContext;
